#!/usr/bin/env ruby
require 'github_api'
require 'clamp'

Clamp do

  option ["-l", "--login"], "LOGIN", "Github Login"
  option ["-p", "--password"], "PASSWORD", "Github Password"
  option ["-m", "--match"], "MATCH", "Repository Matching Name Expression"

  def execute
    client = Github.new(login: login, password: password)

    repositories_to_unwatch
  end

end

